{
 "title": "Istio Log Analyzer",
 "description": "Config checker ",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"istioctl-analyze\", cluster=\"$cluster\"} |= `Error` [5m])"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"istioctl-analyze\", cluster=\"$cluster\"} |= `Warning` [5m])"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{job=\"istioctl-analyze\", cluster=\"$cluster\"} |= `Error`"
    }
   ]
  },
  {
   "title": "Warning Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"istioctl-analyze\", cluster=\"$cluster\"} |= `Warning`"
    }
   ]
  },
  { "title": "All Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "All Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{job=\"istioctl-analyze\", cluster=\"$cluster\"} |= ``"
    }
   ]
  }
 ]
}