apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-analyzer-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istio-analyzer-exporter
  template:
    metadata:
      labels:
        app: istio-analyzer-exporter
    spec:
      containers:
      - name: istio-analyzer-exporter
        image: danilogo/istio-analyzer-exporter:v1.0.6
        env:
        - name: CLUSTER_NAME
          value: "k8s-dev01"
        - name: LOGGING_TOOL_URL
          value: "http://loki.example.com/loki/api/v1/push"
 
